<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DAfKr27Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DAfKr27' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DAfKr27'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CentraleController::delete' => ['privates', '.service_locator.NjaPtIK', 'get_ServiceLocator_NjaPtIKService', true],
            'App\\Controller\\CentraleController::edit' => ['privates', '.service_locator.NjaPtIK', 'get_ServiceLocator_NjaPtIKService', true],
            'App\\Controller\\CentraleController::index' => ['privates', '.service_locator.y7rZdNR', 'get_ServiceLocator_Y7rZdNRService', true],
            'App\\Controller\\CentraleController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CentraleController::show' => ['privates', '.service_locator.v5QvBpQ', 'get_ServiceLocator_V5QvBpQService', true],
            'App\\Controller\\CommuneController::delete' => ['privates', '.service_locator.zDyRHTk', 'get_ServiceLocator_ZDyRHTkService', true],
            'App\\Controller\\CommuneController::edit' => ['privates', '.service_locator.zDyRHTk', 'get_ServiceLocator_ZDyRHTkService', true],
            'App\\Controller\\CommuneController::index' => ['privates', '.service_locator.gcdWpdn', 'get_ServiceLocator_GcdWpdnService', true],
            'App\\Controller\\CommuneController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommuneController::show' => ['privates', '.service_locator.FNZjEzF', 'get_ServiceLocator_FNZjEzFService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ServicesController::delete' => ['privates', '.service_locator.c3c_WSD', 'get_ServiceLocator_C3cWSDService', true],
            'App\\Controller\\ServicesController::edit' => ['privates', '.service_locator.c3c_WSD', 'get_ServiceLocator_C3cWSDService', true],
            'App\\Controller\\ServicesController::index' => ['privates', '.service_locator.LroVcfL', 'get_ServiceLocator_LroVcfLService', true],
            'App\\Controller\\ServicesController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ServicesController::show' => ['privates', '.service_locator.HYpH7s9', 'get_ServiceLocator_HYpH7s9Service', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\UtilisateurController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CentraleController:delete' => ['privates', '.service_locator.NjaPtIK', 'get_ServiceLocator_NjaPtIKService', true],
            'App\\Controller\\CentraleController:edit' => ['privates', '.service_locator.NjaPtIK', 'get_ServiceLocator_NjaPtIKService', true],
            'App\\Controller\\CentraleController:index' => ['privates', '.service_locator.y7rZdNR', 'get_ServiceLocator_Y7rZdNRService', true],
            'App\\Controller\\CentraleController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CentraleController:show' => ['privates', '.service_locator.v5QvBpQ', 'get_ServiceLocator_V5QvBpQService', true],
            'App\\Controller\\CommuneController:delete' => ['privates', '.service_locator.zDyRHTk', 'get_ServiceLocator_ZDyRHTkService', true],
            'App\\Controller\\CommuneController:edit' => ['privates', '.service_locator.zDyRHTk', 'get_ServiceLocator_ZDyRHTkService', true],
            'App\\Controller\\CommuneController:index' => ['privates', '.service_locator.gcdWpdn', 'get_ServiceLocator_GcdWpdnService', true],
            'App\\Controller\\CommuneController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommuneController:show' => ['privates', '.service_locator.FNZjEzF', 'get_ServiceLocator_FNZjEzFService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ServicesController:delete' => ['privates', '.service_locator.c3c_WSD', 'get_ServiceLocator_C3cWSDService', true],
            'App\\Controller\\ServicesController:edit' => ['privates', '.service_locator.c3c_WSD', 'get_ServiceLocator_C3cWSDService', true],
            'App\\Controller\\ServicesController:index' => ['privates', '.service_locator.LroVcfL', 'get_ServiceLocator_LroVcfLService', true],
            'App\\Controller\\ServicesController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ServicesController:show' => ['privates', '.service_locator.HYpH7s9', 'get_ServiceLocator_HYpH7s9Service', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\UtilisateurController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CentraleController::delete' => '?',
            'App\\Controller\\CentraleController::edit' => '?',
            'App\\Controller\\CentraleController::index' => '?',
            'App\\Controller\\CentraleController::new' => '?',
            'App\\Controller\\CentraleController::show' => '?',
            'App\\Controller\\CommuneController::delete' => '?',
            'App\\Controller\\CommuneController::edit' => '?',
            'App\\Controller\\CommuneController::index' => '?',
            'App\\Controller\\CommuneController::new' => '?',
            'App\\Controller\\CommuneController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\ServicesController::delete' => '?',
            'App\\Controller\\ServicesController::edit' => '?',
            'App\\Controller\\ServicesController::index' => '?',
            'App\\Controller\\ServicesController::new' => '?',
            'App\\Controller\\ServicesController::show' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::new' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CentraleController:delete' => '?',
            'App\\Controller\\CentraleController:edit' => '?',
            'App\\Controller\\CentraleController:index' => '?',
            'App\\Controller\\CentraleController:new' => '?',
            'App\\Controller\\CentraleController:show' => '?',
            'App\\Controller\\CommuneController:delete' => '?',
            'App\\Controller\\CommuneController:edit' => '?',
            'App\\Controller\\CommuneController:index' => '?',
            'App\\Controller\\CommuneController:new' => '?',
            'App\\Controller\\CommuneController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\ServicesController:delete' => '?',
            'App\\Controller\\ServicesController:edit' => '?',
            'App\\Controller\\ServicesController:index' => '?',
            'App\\Controller\\ServicesController:new' => '?',
            'App\\Controller\\ServicesController:show' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:new' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
