<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HYpH7s9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HYpH7s9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HYpH7s9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['privates', '.errored..service_locator.HYpH7s9.App\\Entity\\Services', NULL, 'Cannot autowire service ".service_locator.HYpH7s9": it needs an instance of "App\\Entity\\Services" but this type has been excluded in "config/services.yaml".'],
        ], [
            'service' => 'App\\Entity\\Services',
        ]);
    }
}
