<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FNZjEzFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FNZjEzF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FNZjEzF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commune' => ['privates', '.errored..service_locator.FNZjEzF.App\\Entity\\Commune', NULL, 'Cannot autowire service ".service_locator.FNZjEzF": it needs an instance of "App\\Entity\\Commune" but this type has been excluded in "config/services.yaml".'],
        ], [
            'commune' => 'App\\Entity\\Commune',
        ]);
    }
}
