<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NjaPtIKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NjaPtIK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NjaPtIK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'centrale' => ['privates', '.errored..service_locator.NjaPtIK.App\\Entity\\Centrale', NULL, 'Cannot autowire service ".service_locator.NjaPtIK": it needs an instance of "App\\Entity\\Centrale" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'centrale' => 'App\\Entity\\Centrale',
            'entityManager' => '?',
        ]);
    }
}
