<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZDyRHTkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zDyRHTk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zDyRHTk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commune' => ['privates', '.errored..service_locator.zDyRHTk.App\\Entity\\Commune', NULL, 'Cannot autowire service ".service_locator.zDyRHTk": it needs an instance of "App\\Entity\\Commune" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commune' => 'App\\Entity\\Commune',
            'entityManager' => '?',
        ]);
    }
}
