<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V5QvBpQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v5QvBpQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v5QvBpQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'centrale' => ['privates', '.errored..service_locator.v5QvBpQ.App\\Entity\\Centrale', NULL, 'Cannot autowire service ".service_locator.v5QvBpQ": it needs an instance of "App\\Entity\\Centrale" but this type has been excluded in "config/services.yaml".'],
        ], [
            'centrale' => 'App\\Entity\\Centrale',
        ]);
    }
}
