<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCentraleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NjaPtIK.App\Entity\Centrale' shared service.
     *
     * @return \App\Entity\Centrale
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NjaPtIK": it needs an instance of "App\\Entity\\Centrale" but this type has been excluded in "config/services.yaml".');
    }
}
