<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ServicesType' shared autowired service.
     *
     * @return \App\Form\ServicesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ServicesType.php';

        return $container->privates['App\\Form\\ServicesType'] = new \App\Form\ServicesType();
    }
}
