<?php

namespace ContainerA8WT4di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HYpH7s9.App\Entity\Services' shared service.
     *
     * @return \App\Entity\Services
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HYpH7s9": it needs an instance of "App\\Entity\\Services" but this type has been excluded in "config/services.yaml".');
    }
}
