controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_centrale_delete:
    path: '/centrale/delete/{id}'
    controller: App\Controller\CentraleController::delete
