<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA8WT4di\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA8WT4di/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA8WT4di.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA8WT4di\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA8WT4di\App_KernelDevDebugContainer([
    'container.build_hash' => 'A8WT4di',
    'container.build_id' => '197e486e',
    'container.build_time' => 1700805144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA8WT4di');
