<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUN5tTB6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUN5tTB6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUN5tTB6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUN5tTB6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUN5tTB6\App_KernelDevDebugContainer([
    'container.build_hash' => 'UN5tTB6',
    'container.build_id' => '35c36c11',
    'container.build_time' => 1700725893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUN5tTB6');
